
  ## The purpose of this function is to cache the inverse of a matrix
  makeCacheMatrix <- function(x = matrix()) { ## define "matrix" as default
    inv <- NULL                               ## set inv as NULL 
    set <- function(y) {                      ## define the set function 
      x <<- y                                 ## value of matrix in parent environment
      inv <<- NULL                            ## reset inv to NULL when there is a new matrix, 
    }
    get <- function() x                       ## set the get fucntion to return the value of the matrix argument
    
    setinverse <- function(inverse) inv <<- inverse  ## correlates value of inv in parent environment
    getinverse <- function() inv                     ## gets the value of inv
    list(set = set, get = get, setinverse = setinverse, getinverse = getinverse)  ## for referring to the functions with the $ operator
  }
  
  ## The purpose of this function is to compute the inverse of matrix generated by makeCacheMatrix
  ## If the inverse has already been calculated (and the matrix has not changed), then cacheSolve will retrieve the inverse from the cache
  
  cacheSolve <- function(x, ...) { ## Return a matrix that is the inverse of 'x'
    inv <- x$getinverse()
    if(!is.null(inv)) {
      message("getting cached data")
      return(inv)
    }
    data <- x$get()
    inv <- solve(data, ...)
    x$setinverse(inv)
    inv
  }
